apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-prod
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
  sources:
  - chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.16.2
    helm:
      releaseName: sealed-secrets-prod
      valueFiles:
      - $values/environments/helm-values-production.yaml
  - repoURL: 'https://github.com/Qlik-Guillaume-Tessier/kubeseal-argo.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secret-prod
